export default function About() {
  return (
    <div className="prose">
      <h1>About</h1>
      <p>
        I'm Hipvan — NUS Computer Science master's graduate with a background in
        data analysis and a passion for AI.
      </p>
      <p>
        I'm currently exploring AI engineering, reinforcement learning, and
        building tools that bridge the gap between messy notes and polished
        ideas.
      </p>
      <p>
        This blog is partly generated by an{" "}
        <a href="https://github.com/hipvan">Obsidian Agent</a> I built — it
        reads my Obsidian notes and helps draft blog posts. The whole process is
        open source.
      </p>
      <h2>What I write about</h2>
      <ul>
        <li>AI / ML engineering and paper readings</li>
        <li>Building projects and learning in public</li>
        <li>Career reflections and job search notes</li>
      </ul>
    </div>
  );
}
